account/urls.py
from django.urls import path, include
from .views import register


urlpatterns = [
    # path('login/', user_login, name='login'),
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register')
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

ru/urls.py
from django.urls import path
from .views import home, catalog, shopper, bag, organizer, backpack, umra, cosmeticBag, giftBag, envelopesForBooks, search_results




urlpatterns = [
    path('', home, name='home'),
    path('products/', catalog, name='catalog'),
    path('products/shoppers/', shopper, name='shopper'),
    path('products/bags/', bag, name='bag'),
    path('products/organizer/', organizer, name='organizer'),
    path('products/backpack/', backpack, name='backpack'),
    path('products/umra/', umra, name='umra'),
    path('products/cosmeticBag/', cosmeticBag, name='cosmeticBag'),
    path('products/giftBag/', giftBag, name='giftBag'),
    path('products/envelopesForBooks/', envelopesForBooks, name='envelopesForBooks'),
    path('results', search_results, name='search_results'),
]

safar_fe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('ru/', include('ru.urls')),
    path('account/', include('account.urls')),
    path('', RedirectView.as_view(url='/ru/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

ru/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class allProduct(models.Model):
    title = models.CharField(max_length=30)
    image = models.ImageField(upload_to='product/%Y/%m/%d/',blank=True)
    price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)


    class Meta:
        ordering = ['category']
    
    def __str__(self):
        return self.title
    

account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Пароль указан не верно')
        return cd['password2']

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

account/views.py
from django.shortcuts import render
from .forms import  UserRegistrationForm


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password1'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form':user_form})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ru.models import allProduct
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(allProduct, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(allProduct, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

ru/views.py
from django.shortcuts import render
from .models import allProduct, Category
from fuzzywuzzy import fuzz
from unidecode import unidecode
from cart.forms import CartAddProductForm

def search_results(request):
    search = request.GET.get('search', '')
    results = []


    if search:
        normalized_query = unidecode(search).lower()
        categories = Category.objects.all()
        matching_categories = []

        for category in categories:
            normalized_category_name = unidecode(category.name).lower()
            match_ratio = fuzz.partial_ratio(normalized_query, normalized_category_name)
            if match_ratio > 70:
                matching_categories.append(category)

        results = allProduct.objects.filter(category__in=matching_categories).order_by('-date')
    return render(request, 'ru/search_results.html', {'products': results, 'search': search})



def home(request):
    cart_product_form = CartAddProductForm()
    allItems = allProduct.objects.all().order_by('-date')[:12]
    context = {
        'allItems':allItems, 
        'cart_product_form':cart_product_form,
        }
    return render(request, 'ru/index.html', context)


def catalog(request):
    allItems = allProduct.objects.all().order_by('-date')
    return render(request, 'ru/allProductTemplates/catalog.html', {'allItems':allItems})

def shopper(request):
    shopper = Category.objects.get(name='Шопперы')
    allshopper = allProduct.objects.filter(category=shopper).order_by('-date')
    return render(request, 'ru/allProductTemplates/shopper.html', {'allshopper':allshopper})

def bag(request):
    bag = Category.objects.get(name='Сумки')
    allbag = allProduct.objects.filter(category=bag).order_by('-date')
    return render(request, 'ru/allProductTemplates/sumka.html', {'allbag':allbag})

def organizer(request):
    organizer = Category.objects.get(name='Органайзеры')
    allorganizer = allProduct.objects.filter(category=organizer).order_by('-date')
    return render(request, 'ru/allProductTemplates/organizer.html', {'allorganizer':allorganizer})

def backpack(request):
    backpack = Category.objects.get(name='Рюкзаки')
    allbackpack = allProduct.objects.filter(category=backpack).order_by('-date')
    return render(request, 'ru/allProductTemplates/backpack.html', {'allbackpack':allbackpack})

def umra(request):
    umra = Category.objects.get(name='Умра Safari')
    allUmra = allProduct.objects.filter(category=umra).order_by('-date')
    return render(request, 'ru/allProductTemplates/umra.html', {'allUmra':allUmra})

def cosmeticBag(request):
    cosmeticBag = Category.objects.get(name='Косметички')
    allCosmeticBag = allProduct.objects.filter(category=cosmeticBag).order_by('-date')
    return render(request, 'ru/allProductTemplates/cosmeticBag.html', {'allCosmeticBag':allCosmeticBag})

def giftBag(request):
    giftBag = Category.objects.get(name='Подарочные Мешочки')
    allGiftBag = allProduct.objects.filter(category=giftBag).order_by('-date')
    return render(request, 'ru/allProductTemplates/giftBag.html', {'allGiftBag':allGiftBag})

def envelopesForBooks(request):
    envelopesForBooks = Category.objects.get(name='Конверты Для Книг')
    allenvelopesForBooks = allProduct.objects.filter(category=envelopesForBooks).order_by('-date')
    return render(request, 'ru/allProductTemplates/envelopesForBooks.html', {'allenvelopesForBooks':allenvelopesForBooks})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
SafarFE - Корзина
{% endblock %}

{% block content %}
<h1>Ваша корзина</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Фото</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за единицу</th>
            <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>
                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                    <input type="submit" value="Remove">
                    {% csrf_token %}
                </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Вся стоимость</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}сум</td>
        </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url "home" %}" class="button light">Продолжить шоппинг</a>
    <a href="#" class="button">Заказать</a>
</p>
{% endblock %}

ru/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ru/css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="block_nav">
        {% block nav %}
        <nav>
            <a href="{% url 'home' %}" class="Logo">SafarFE</a>
            <div class="box_katalog">
                <a class="openPopup" href="{% url 'catalog' %}">Каталог</a>
            </div>
            <form style="height: 40px;" method="get" action="{% url 'search_results' %}">
                <input type="text" name="search" class="inp" placeholder="Поиск по категориям..."
                    value="{{ request.GET.search }}">
                <button type="submit" class="search_btn">Искать</button>
            </form>
            <div class="box_popup_account">
                {% if user.is_authenticated %}
                <button id="openPopupAccount" class="openPopupAccount">
                    {{ user }}
                </button>
                <div id="popup_account" class="popup_account">
                    <a href="{% url 'cart:cart_detail' %}">Корзина</a>
                    <a href="{% url 'password_change' %}">Сменить Пароль</a>
                    <a href="{% url 'logout' %}">Выйти с аккаунта</a>
                </div>
                {% else %}
                <a class="login_logout" href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
            <div class="box_katalog_laguage">
                <button id="openPopup2" class="openPopup2">
                    <img id="openPopupImage" src="{% static 'ru/img/ru.svg' %}">
                </button>
                <div id="popup2" class="popup2">
                    <a href="" class="hover2" style="display: flex;justify-content: center; align-items: center;">
                        <img style="width: 26px; height: 20px; border-radius: 3px;" src="{% static 'ru/img/uz.svg' %}">
                    </a>
                    <a href="" class="hover2" style="display: flex;justify-content: center; align-items: center;">
                        <img style="width: 26px; height: 20px; border-radius: 3px;"
                            src="{% static 'ru/img/usa.avif' %}">
                    </a>
                </div>
            </div>

        </nav>
        {% endblock %}
    </div>



    <div class="block_content">
        {% block content %}

        {% endblock %}
    </div>



    <div class="block_footer">
        {% block footer %}
        <footer class="footer">
            <div class="box_logo_ooo">
                <a href="{% url 'home' %}" class="Logo">Safar_FE</a>
                <a href="tel:+998977824411" class="voprosi">Есть Вопросы? Звоните: <br>+998 97 782 44 11</a>
            </div>
            <div class="box_tg">
                <a target="_blank" href="https://t.me/safar_fe"><img src="{% static 'ru/img/tg.svg' %}"></a>
                <a height: 50px; target="_blank"
                    href="https://www.instagram.com/safar_fe?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="><img
                        src="{% static 'ru/img/insta.svg' %}"></a>
            </div>
            <p class="ooo">© ООО «Safar_FE»</p>
        </footer>
        {% endblock %}
    </div>

    <script src="{% static 'ru/js/popups.js' %}"></script>
    <script src="{% static 'ru/js/fixed-block.js' %}"></script>
    <script src="{% static 'ru/js/loader.js' %}"></script>
    <script src="{% static 'ru/js/placeholders.js' %}"></script>
</body>

</html>

ru/templates/ru/allProductTemplates/backpack.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}SafarFE - Каталог{% endblock %}

{% block content %}
<section class="sec2">
    <div class="allCategories">
        <h1><img style="width: 34px;height: 34px; margin-top: 7px;" src="{% static 'ru/img/catalog.svg' %}">Все катогории товаров</h1>
        <a style="margin-top: 20px; color: #800000;" href="{% url 'home' %}">На главную<img style="margin-top: 2px;" src="{% static 'ru/img/right arrow.svg' %}" ></a>
    </div>
    <div class="twoblocks">
        <div class="block1">
            <div id="fixed-block" class="scrollbar">
                <a href="{% url 'catalog' %}" class="ablockcatalog">Все Товары</a>
                <a href="{% url 'shopper' %}" class="ablockcatalog">Шопперы</a>
                <a href="{% url 'bag' %}" class="ablockcatalog">Сумки</a>
                <a href="{% url 'organizer' %}" class="ablockcatalog">Огранайзеры</a>
                <a href="{% url 'backpack' %}" class="ablockcatalog show">Рюкзаки</a>
                <a href="{% url 'umra' %}" class="ablockcatalog">Умра Safar</a>
                <a href="{% url 'cosmeticBag' %}" class="ablockcatalog">Косметички</a>
                <a href="{% url 'giftBag' %}" class="ablockcatalog">Подарочные мешочки</a>
                <a href="{% url 'envelopesForBooks' %}" class="ablockcatalog">Конверты для книг</a>
            </div>
        </div>
        <div id="block2" class="block2">
            {% for allbackpack in allbackpack %}
            <div class="product_box">
                <p class="p_product">{{ allbackpack.price|format_price }} cум</p>
                <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
                    src="{{ allbackpack.image.url }}">
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

ru/templates/ru/allProductTemplates/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}SafarFE - Каталог{% endblock %}

{% block content %}
<div class="loader">SafarFE</div>
<section class="sec2">
    <div class="allCategories">
        <h1 style="font-size: 30px; color: #800000;"><img style="width: 34px;height: 34px; margin-top: 7px;"
                src="{% static 'ru/img/catalog.svg' %}">Все катогории товаров</h1>
        <a style="margin-top: 20px; color: #800000;" href="{% url 'home' %}">На главную<img style="margin-top: 2px;"
                src="{% static 'ru/img/right arrow.svg' %}"></a>
    </div>
    <div class="twoblocks">
        <div class="block1">
            <div id="fixed-block" class="scrollbar">
                <a href="{% url 'catalog' %}" class="ablockcatalog show">Все Товары</a>
                <a href="{% url 'shopper' %}" class="ablockcatalog">Шопперы</a>
                <a href="{% url 'bag' %}" class="ablockcatalog">Сумки</a>
                <a href="{% url 'organizer' %}" class="ablockcatalog">Огранайзеры</a>
                <a href="{% url 'backpack' %}" class="ablockcatalog">Рюкзаки</a>
                <a href="{% url 'umra' %}" class="ablockcatalog">Умра Safari</a>
                <a href="{% url 'cosmeticBag' %}" class="ablockcatalog">Косметички</a>
                <a href="{% url 'giftBag' %}" class="ablockcatalog">Подарочные мешочки</a>
                <a href="{% url 'envelopesForBooks' %}" class="ablockcatalog">Конверты для книг</a>
            </div>
        </div>
        <div id="block2" class="block2">
            {% for allItem in allItems %}
            <div class="product_box">
                <p class="p_product">{{ allItem.price|format_price }} сум</p>
                <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
                    src="{{ allItem.image.url }}">
            </div>
            {% endfor %}
        </div>
</section>
{% endblock %}

ru/templates/ru/allProductTemplates/cosmeticBag.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}SafarFE - Каталог{% endblock %}

{% block content %}
<section class="sec2">
    <div class="allCategories">
        <h1 style="font-size: 30px; color: #800000;"><img style="width: 34px;height: 34px; margin-top: 7px;"
                src="{% static 'ru/img/catalog.svg' %}">Все катогории товаров</h1>
        <a style="margin-top: 20px; color: #800000;" href="{% url 'home' %}">На главную<img style="margin-top: 2px;"
                src="{% static 'ru/img/right arrow.svg' %}"></a>
    </div>
    <div class="twoblocks">
        <div class="block1">
            <div id="fixed-block" class="scrollbar">
                <a href="{% url 'catalog' %}" class="ablockcatalog">Все Товары</a>
                <a href="{% url 'shopper' %}" class="ablockcatalog">Шопперы</a>
                <a href="{% url 'bag' %}" class="ablockcatalog">Сумки</a>
                <a href="{% url 'organizer' %}" class="ablockcatalog">Огранайзеры</a>
                <a href="{% url 'backpack' %}" class="ablockcatalog">Рюкзаки</a>
                <a href="{% url 'umra' %}" class="ablockcatalog">Умра Safari</a>
                <a href="{% url 'cosmeticBag' %}" class="ablockcatalog show">Косметички</a>
                <a href="{% url 'giftBag' %}" class="ablockcatalog">Подарочные мешочки</a>
                <a href="{% url 'envelopesForBooks' %}" class="ablockcatalog">Конверты для книг</a>
            </div>
        </div>
        <div id="block2" class="block2">
            {% for allCosmeticBag in allCosmeticBag %}
            <div class="product_box">
                <p class="p_product">{{ allCosmeticBag.price|format_price }} сум</p>
                <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
                    src="{{ allCosmeticBag.image.url }}">
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

ru/templates/ru/allProductTemplates/envelopesForBooks.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}SafarFE - Каталог{% endblock %}

{% block content %}
<section class="sec2">
    <div class="allCategories">
        <h1><img style="width: 34px;height: 34px; margin-top: 7px;" src="{% static 'ru/img/catalog.svg' %}">Все катогории товаров</h1>
        <a style="margin-top: 20px; color: #800000;" href="{% url 'home' %}">На главную<img style="margin-top: 2px;" src="{% static 'ru/img/right arrow.svg' %}" ></a>
    </div>
    <div class="twoblocks">
        <div class="block1">
            <div id="fixed-block" class="scrollbar">
                <a href="{% url 'catalog' %}" class="ablockcatalog">Все Товары</a>
                <a href="{% url 'shopper' %}" class="ablockcatalog">Шопперы</a>
                <a href="{% url 'bag' %}" class="ablockcatalog">Сумки</a>
                <a href="{% url 'organizer' %}" class="ablockcatalog">Огранайзеры</a>
                <a href="{% url 'backpack' %}" class="ablockcatalog">Рюкзаки</a>
                <a href="{% url 'umra' %}" class="ablockcatalog">Умра Safari</a>
                <a href="{% url 'cosmeticBag' %}" class="ablockcatalog">Косметички</a>
                <a href="{% url 'giftBag' %}" class="ablockcatalog">Подарочные мешочки</a>
                <a href="{% url 'envelopesForBooks' %}" class="ablockcatalog show">Конверты для книг</a>
            </div>
        </div>
        <div id="block2" class="block2">
            {% for allenvelopesForBooks in allenvelopesForBooks %}
            <div class="product_box">
                <p class="p_product">{{ allenvelopesForBooks.price|format_price }} сум</p>
                <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
                    src="{{ allenvelopesForBooks.image.url }}">
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

ru/templates/ru/allProductTemplates/giftBag.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}SafarFE - Каталог{% endblock %}

{% block content %}
<section class="sec2">
    <div class="allCategories">
        <h1><img style="width: 34px;height: 34px; margin-top: 7px;" src="{% static 'ru/img/catalog.svg' %}">Все катогории товаров</h1>
        <a style="margin-top: 20px; color: #800000;" href="{% url 'home' %}">На главную<img style="margin-top: 2px;" src="{% static 'ru/img/right arrow.svg' %}" ></a>
    </div>
    <div class="twoblocks">
        <div class="block1">
            <div id="fixed-block" class="scrollbar">
                <a href="{% url 'catalog' %}" class="ablockcatalog">Все Товары</a>
                <a href="{% url 'shopper' %}" class="ablockcatalog">Шопперы</a>
                <a href="{% url 'bag' %}" class="ablockcatalog">Сумки</a>
                <a href="{% url 'organizer' %}" class="ablockcatalog">Огранайзеры</a>
                <a href="{% url 'backpack' %}" class="ablockcatalog">Рюкзаки</a>
                <a href="{% url 'umra' %}" class="ablockcatalog">Умра Safari</a>
                <a href="{% url 'cosmeticBag' %}" class="ablockcatalog">Косметички</a>
                <a href="{% url 'giftBag' %}" class="ablockcatalog show">Подарочные мешочки</a>
                <a href="{% url 'envelopesForBooks' %}" class="ablockcatalog">Конверты для книг</a>
            </div>
        </div>
        <div id="block2" class="block2">
            {% for allGiftBag in allGiftBag %}
            <div class="product_box">
                <p class="p_product">{{ allGiftBag.price|format_price }} сум</p>
                <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
                    src="{{ allGiftBag.image.url }}">
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

ru/templates/ru/allProductTemplates/organizer.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}SafarFE - Каталог{% endblock %}

{% block content %}
<section class="sec2">
    <div class="allCategories">
        <h1><img style="width: 34px;height: 34px; margin-top: 7px;" src="{% static 'ru/img/catalog.svg' %}">Все катогории товаров</h1>
        <a style="margin-top: 20px; color: #800000;" href="{% url 'home' %}">На главную<img style="margin-top: 2px;" src="{% static 'ru/img/right arrow.svg' %}" ></a>
    </div>
    <div class="twoblocks">
        <div class="block1">
            <div id="fixed-block" class="scrollbar">
                <a href="{% url 'catalog' %}" class="ablockcatalog">Все Товары</a>
                <a href="{% url 'shopper' %}" class="ablockcatalog">Шопперы</a>
                <a href="{% url 'bag' %}" class="ablockcatalog">Сумки</a>
                <a href="{% url 'organizer' %}" class="ablockcatalog show">Огранайзеры</a>
                <a href="{% url 'backpack' %}" class="ablockcatalog">Рюкзаки</a>
                <a href="{% url 'umra' %}" class="ablockcatalog">Умра Safari</a>
                <a href="{% url 'cosmeticBag' %}" class="ablockcatalog">Косметички</a>
                <a href="{% url 'giftBag' %}" class="ablockcatalog">Подарочные мешочки</a>
                <a href="{% url 'envelopesForBooks' %}" class="ablockcatalog">Конверты для книг</a>
            </div>
        </div>
        <div id="block2" class="block2">
            {% for allorganizer in allorganizer %}
            <div class="product_box">
                <p class="p_product">{{ allorganizer.price|format_price }} сум</p>
                <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
                    src="{{ allorganizer.image.url }}">
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

ru/templates/ru/index.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
<title>{% block title %}SafarFE - Главное{% endblock title %}</title>
{% block content %}
<div class="loader">SafarFE</div>
<section class="sec2">
    <div class="box_sec2">
        <div class="prod">
            <div class="box_catalog_txt">
                <img src="{% static 'ru/img/catalog.svg' %}" style=" margin-top: 11px;width: 35px;height: 35px;">
                Каталог
            </div>
            <a href="{% url 'catalog' %}" class="vse">
                <p style="width: 145px; height: 25px;">Полный Список <img src="{% static 'ru/img/right arrow.svg' %}">
                </p>
            </a>
        </div>
    </div>
    <div class="box_sec2_prod">
        {% for allItem in allItems %}
        <div class="product_box">
            <p class="p_product">{{ allItem.price|format_price }} сум</p>
            <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
                src="{{ allItem.image.url }}">
            </div>
            <form action="{% url "cart:add" product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Add to cart">
                </form>
        {% endfor %}
    </div>
</section>
{% endblock %}

ru/templates/ru/search_results.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}SafarFE - {{ search }}{% endblock title %}

{% block content %}

<h1 class="h1Search">{{ search }}</h1>
<div class="box_sec2_prod">
    {% for product in products %}
    <div class="product_box">
        <p class="p_product">{{ product.price|format_price }} сум</p>
        <img style="width: 300px; height: 300px; border: none; border-radius: 5px; z-index: 1;"
            src="{{ product.image.url }}">
    </div>
    {% empty %}
    <div class="boxPSearch">
    <p class="pSearch">Нет товара данной категории.</p>
    </div>
    {% endfor %}
</div>

{% endblock content %}